### ISSUE TITLE
Book space and set final dates for workshop

### ISSUE THREAD

**Issue by nicolevasilevsky** [OHSU-Library/DataScienceInstitute#1]
- [x] Contact White Stag building about renting space
- [x] set final dates

**Comment by nicolevasilevsky** [comment]
see [scheduling spreadsheet](https://docs.google.com/spreadsheets/d/1OQ7U3sWKznhL_yDKWc6G9PGon_6yFLLPzn11rf3NaIU/edit#gid=0)

**Comment by nicolevasilevsky** [comment]
Jackie contacted White stag on 05/31

**Comment by nicolevasilevsky** [comment]
White Stag room either Tues-Thurs (Oct 10-12) or  Wed-Fri (Oct 11-13)
Room 152
49 people max

Lunch on our own

**Comment by rchampieux** [comment]
@wirzj reported to Letisha that OCTRI may want their trainees to attend the institute as part of they're mandatory training; however, the dates above may not work for this.
## # @wirzj can you please follow up with the exact dates that will work.

**Comment by nicolevasilevsky** [comment]
potential dates at White Stag:
Oct 11, 12
Oct 19, 20
Oct 23, 24
Nov 6, 7, 8

Could do 2 days with breakout sessions.

@rchampieux @wirzj @lrwyatt @zeigenl please respond to doodle poll: https://doodle.com/poll/saq2mrrkdpwbbbdr

**Comment by rchampieux** [comment]
@nicolevasilevsky I'm confused about the poll.  Don't we need to wait to hear from @wirzj about OCTRI's preferences?

**Comment by nicolevasilevsky** [comment]
Jackie talked to OCTRI and they said any dates except in Sept would work for them. And sounds like these are the dates that are currently available at the White Stag.

**Comment by rchampieux** [comment]
I see, thanks!

**Comment by lrwyatt** [comment]
@rchampieux should we reach out to PNW Data Curators to gauge interest in tandem event planning for October? They were talking about fall/November in the email.

**Comment by nicolevasilevsky** [comment]
sounds like the November dates may work best for our group.

**Comment by rchampieux** [comment]
Yes, let's do that @lrwyatt
