### ISSUE TITLE
work on logo for website/materials

### ISSUE THREAD

**Issue by nicolevasilevsky** [OHSU-Library/DataScienceInstitute#12]
use Canva

**Comment by jmcmurry** [comment]
canva is pretty terrible, tbh. I would stick with illustrator over dropbox unless you're super restricted with licenses.

**Comment by nicolevasilevsky** [comment]
need to update favicon too

**Comment by nicolevasilevsky** [comment]
here are some draft logos: https://ohsu.box.com/s/w6ghtrk1k22i00y43yxjc14rnm49v65y

**Comment by nicolevasilevsky** [comment]
new color scheme for logos below
![image](https://user-images.githubusercontent.com/6722114/27979359-45181e04-632a-11e7-8ce0-a0552124d2bd.png)

Please recommend other color schemes if you don't like these colors, or please update the logo in Box here: https://ohsu.box.com/s/wyscm7c9363y38w83ur51047vfx4iuuw

**Comment by jmcmurry** [comment]
I love it! Nice job Nicole.
I do question the shortening of the acronym to ODSI though. At first glance I thought it was OHDSI which is in a similar space? https://ohdsi.org/
