### ISSUE TITLE
Recruit instructors

### ISSUE THREAD

**Issue by nicolevasilevsky** [OHSU-Library/DataScienceInstitute#2]
dependent on #1, #3 
- [x] assign instructors to topics

**Comment by nicolevasilevsky** [comment]
[Tentative instructors are here](https://docs.google.com/spreadsheets/d/1FMjL_cvRRncPTElGp8YfN1roafKabiEjEth10uPW01Q/edit#gid=0)

**Comment by nicolevasilevsky** [comment]
Draft email to instructors: https://docs.google.com/document/d/12hLEYyWwykn0Ffne4huwsjilVklaaYgonDyAKtMrRcM/edit

**Comment by nicolevasilevsky** [comment]
@wirzj could you work on a boiler plate invite to invite the instructors to teach? I started a draft template here: https://docs.google.com/document/d/12hLEYyWwykn0Ffne4huwsjilVklaaYgonDyAKtMrRcM/edit 

Then we can assign each team member to invite each instructor and track in this spreadsheet: 
https://docs.google.com/spreadsheets/d/1FMjL_cvRRncPTElGp8YfN1roafKabiEjEth10uPW01Q/edit#gid=0

**Comment by nicolevasilevsky** [comment]
template and assignments have been updated. But feel free to edit.

**Comment by nicolevasilevsky** [comment]
GIS section:
Overview 90 min presentation that discusses previous project/outcomes and ties into a free online guidebook that makes material assessable for others to learn from 
http://www.hackoregon.org/
- web cartography
- data science/geospatial data/spatial analytics (highest priority) 
- OHSU researchers take their classes and volunteer, could potentially send someone from the library and train them and they could teach the class in the ODSI
  - would need to apply, go through phone screening/an interview. Could be scholarship options (up to full scholarship).

Next steps:
- @zeigenl Need summary of what is needed from us, note the Honorarium, benefits of participation for the instructors
- HackOregon will send us more info about scholarships
- @zeigenl Need to send out info to the Library staff about potentially taking the course this summer and then teaching in the Inst this fall
   - Laura has people in mind from the Public Health school
   - ask folks in ODG?

**Comment by zeigenl** [comment]
Hi all - Nicole and I had a good discussion this morning with the people at Hack Oregon (see Nicole's notes above). 

We need to provide Hack Oregon with some estimate of the amount of honoraria we could provide in the case one of their instructors were to provide a 90-minute session for us on these topics.

We also need to provide them with a list of potential people at OHSU (public health, ODG, other) who might be interested in applying to go through one of their classes this summer (scholarships available, per Nicole's notes) and potential be the one to provide this instruction at ODSI.

Nicole - let me know if I am missing anything here.

**Comment by zeigenl** [comment]
Nicole - who in ODG do you think would be potentially interested in this or do you just want to email all of them?

**Comment by nicolevasilevsky** [comment]
I was thinking we could email everyone but Lilly, Dan, Kent and Tom come to mind because they have coding experience.

**Comment by zeigenl** [comment]
Sounds good. Do you want me to provide you with a listing of the potential public health people and have you send the email or do you want me to include the ODG people in the email I could send to the public health people?

**Comment by nicolevasilevsky** [comment]
It would probably be better for you to contact the public health people, since you already know them. If you could email the ODG folks too, that would be great. I can follow up if we don't hear back from anyone.

**Comment by zeigenl** [comment]
Sounds good. I will craft a draft to send. Would you and/or others like to see the draft before I send it to the public health people and ODG people?

**Comment by nicolevasilevsky** [comment]
Sure! Thanks Laura!

**Comment by nicolevasilevsky** [comment]
Update 07/07/17
- [x] asked Lilly to teach data standards
- [x] Robin to talk to Dave about his session
- [x] Laura working to confirm a GIS instructor
- [ ] Robin to confirm Max and/or Danielle will teach github session
