### ISSUE TITLE
Create registration form

### ISSUE THREAD

**Issue by nicolevasilevsky** [OHSU-Library/DataScienceInstitute#8]

**Comment by nicolevasilevsky** [comment]
- [ ] need to link registration form to the website

**Comment by nicolevasilevsky** [comment]
Draft registration form is here:
https://docs.google.com/forms/d/1JPGlNYplKLbK7DB5-sjueHJG0sc8Dm-hZYlfUwCNydE/edit?usp=drive_web 

Goal is to open registration by early August

**Comment by lrwyatt** [comment]
I think this draft looks great! What do you think about trying to see if people would pre-select an application workshop for day 3 via the reg form? To get a sense of numbers. Or was that the intention of the methods familiarity question? Also as a reminder, elements we said we'd capture (per our application) which will contribute to evaluating outcomes:

- discipline
- occupation (is this the title/position question? and how does this differ from the "are you a...[check the box]" question)?
- career stage
- data science experience

**Comment by nicolevasilevsky** [comment]
@wirzj - do you know how many people fit in each room for the two tracks?

@lrwyatt I like the idea of asking folks to preselect their tracks for day 3 
Also, thanks for checking the grant, I'll add a section for discipline, I think occupation is captured with the current role (Robin updated that from 'are you a...'), I will add career stage, and I think we capture data science experience with the checklist, yes?

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] add group email address, dependent on #16 
- [ ] add logo, dependent on #12 
- [ ] check all the links on the registration form before we send it out.

**Comment by nicolevasilevsky** [comment]
@lrwyatt @rchampieux @wirzj @zeigenl 
Not really sure how to capture career stage, please review
